name: prometheus-exporter
version: "1.0"
main: com.danidipp.prometheusexporter.PrometheusExporter
api-version: "1.20"
authors:
  - DaniDipp
description: Exporting LoM/DvZ server metrics to Prometheus
